namespace: postgres-operator

secretGenerator:
  - name: pgo-s3-creds
    files:
      - s3.conf

generatorOptions:
  disableNameSuffixHash: true

resources:
  # - leetdesk_backend.yaml
  # - datomic.yaml
  # - keycloak.yaml
  # - mattermost.yaml
