apiVersion: postgres-operator.crunchydata.com/v1beta1
kind: PostgresCluster
metadata:
  name: leetdesk-backend
spec:
  image: registry.developers.crunchydata.com/crunchydata/crunchy-postgres:ubi8-14.5-1
  postgresVersion: 14
  instances:
    - dataVolumeClaimSpec:
        accessModes:
          - "ReadWriteOnce"
        resources:
          requests:
            storage: 1Gi
  users:
    - name: leetdesk
      databases:
        - leetdesk
      password:
        type: AlphaNumeric
    - name: postgres
      password:
        type: AlphaNumeric
  patroni:
    dynamicConfiguration:
      postgresql:
        pg_hba:
          - host all all 0.0.0.0/0 md5
  backups:
    pgbackrest:
      image: registry.developers.crunchydata.com/crunchydata/crunchy-pgbackrest:ubi8-2.40-1
      configuration:
        - secret:
            name: pgo-s3-creds
      global:
        repo1-path: /pgbackrest/postgres-operator/datomic/repo1
        repo1-s3-uri-style: path
      repos:
        - name: repo1
          s3:
            bucket: "database-backups"
            endpoint: "https://s3.schnaq.com"
            region: "eu-west"
